Update the nav elements active status using Pathname
EddieHubCommunity/HealthCheck pull request #24
Opened 2024-07-12 19:14 UTC by Muhammad-Owais-Warsi

## Fixes Issue Closes #17 

## Changes proposed
 - Used `usePathname` to get the current path.
 - Using that current path , I update the tailwind dynamically.

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

![Screenshot 2024-07-13 004356](https://github.com/user-attachments/assets/ccfda779-9a81-4509-8b56-53d3c0cc0d9d)

2024-07-12 19:23 UTC, eddiejaoude requested changes
Thank you for the contribution 👍 

Why is there `"use client"` everywhere?

2024-07-12 19:25 UTC, Muhammad-Owais-Warsi commented
> Thank you for the contribution 👍
> 
> Why is there `"use client"` everywhere?

Ah, actually i was testing some other functions too. I'll correct them... Thanks for letting me know

2024-07-12 19:40 UTC, Muhammad-Owais-Warsi commented
@eddiejaoude on removing the `use client` from those places raise errors. Like `Object.groupBy` is not a function etc..

2024-07-12 20:24 UTC, eddiejaoude commented
Please go through and check your changes, "use client" should not be required. I would recommend checking your local node version as this might be causing the problem.

2024-07-13 07:12 UTC, Muhammad-Owais-Warsi commented
@eddiejaoude please review and let me know if any changes required.

2024-07-13 09:27 UTC, eddiejaoude commented
@Muhammad-Owais-Warsi please recheck each of your changes and make sure you are happy with them, because there are so many unnecessary changes

2024-07-13 10:44 UTC, Muhammad-Owais-Warsi commented
@eddiejaoude to me it seems to be fine.

2024-07-13 10:53 UTC, eddiejaoude commented
I will comment a few examples in line

2024-07-13 10:53 UTC, eddiejaoude commented on src/app/repo/status/page.js
> +
I don't think this change is required?

2024-07-13 10:54 UTC, eddiejaoude commented on src/app/repo/status/page.js
> +  const results = checks(repo);
I don't think this change is required?

2024-07-13 10:59 UTC, eddiejaoude requested changes
Thank you for making further changes, but more are still required. I have left some example inline comments

Please recheck that all changes in your PR are changes you are happy with, such as extra line changes resulting in files being included in your PR that should not be

2024-07-13 11:08 UTC, Muhammad-Owais-Warsi commented
> Thank you for making further changes, but more are still required. I have left some example inline comments
> 
> Please recheck that all changes in your PR are changes you are happy with, such as extra line changes resulting in files being included in your PR that should not be

Sorry for the inconvenience, I'll recheck and let you know.

2024-07-13 11:25 UTC, Muhammad-Owais-Warsi commented
@eddiejaoude Please review , I don't think anything should cause any problem now

2024-07-21 12:38 UTC, eddiejaoude commented
Thank you for your contribution. As there were still unnecessary changes this PR could not be merge, and now as there are conflicts also, I have made a PR to solve this issue https://github.com/EddieHubCommunity/HealthCheck/pull/43, so I will close this PR.

Hopefully my PR will highlight the changes required, for example the existing condition was the main change only required
https://github.com/EddieHubCommunity/HealthCheck/pull/43/files#diff-6a1559e4b25e80b6a3b7c9c6b7d24db73177617ee8efbc935fae6fd8a59d1667R170

2024-07-21 12:38 UTC, closed without merging

2024-07-22 13:41 UTC, Muhammad-Owais-Warsi commented
Thanks @eddiejaoude , will try to improve next time

2024-07-22 15:46 UTC, eddiejaoude commented
Thanks @Muhammad-Owais-Warsi for the collaboration